Transient growth f5
AllenCell/nuc-morph-analysis pull request #33
Opened 2024-10-04 17:37 UTC by cfrick13

# General overview
- this code performs new analysis with `dxdt_48_volume` (nuclear transient growth rate) across cell cycle for Figure 5 panel F, and suppFig9 and 10. The analysis is mostly simple and is captured in `nuc_morph_analysis/analyses/volume/plot_help.py / plot_dxdt_over_time_by_cell_cycle.py`

-this code also introduces a new workflow for identifying short-lived dramatic dips in nuclear volume (suppFigS10). 

# Volume dip detection and removal (new features and where they come from)
 - global_dataset_filtering functions
     ```
     add_volume_change_over_25_minute_window --> 'volume_change_over_25_minutes'
     ```

 - filter_out_dips.run_script(df_full) -->
     ```
    'volume_dip_peak_mask_at_region', # boolean array, true at all points within peak region(s)
    'volume_dip_peak_mask_at_center', # boolean array, true at all peak centers
    'volume_dip_has_peak', # boolean array, true at all points if there is a peak
    'volume_dip_volume_change_at_center', # magnitude value at each peak center (left_base - peak)
    'volume_dip_volume_change_at_region', # magnitude values at all points within peak region(s) (left_base - peak)
    'volume_dip_width_at_center', # width of the peak at the peak center index
    'volume_dip_width_at_region', # width of the peak at all indices in the peak region
    'volume_dip_max_volume_change', # maximum magnitude value (at all points in array)
    'volume_dip_peak_id_at_center', # peak id at the peak center index
    'volume_dip_peak_id_at_region', # peak id at all indices in the peak region
    'volume_dip_total_number', # total number of peaks
    "volume_dip_removed_um_unfilled", # dips or jumps removed (refilled with nans)
    
    'volume_dips_removed_um_unfilled' # volume trajectories with peak (volume dip) regions removed
     ```

- then compute growth rate to get -->
     ```
     `dxdt_48_volume_dips_removed_um_unfilled`
     ```

 - and compute neighbors to get -->
     ```
     'neighbor_avg_dxdt_48_volume_dips_removed_um_unfilled_90um'
     'neighbor_avg_dxdt_48_volume_dips_removed_um_unfilled_whole_colony'
     ```

# New/updated figures generated in this code
### Figure 5 panel F, G, H
<img width="678" alt="image" src="https://github.com/user-attachments/assets/2ac5922d-158a-4771-9737-18f95d9833e5">
* _note: only change to H was N value correction_

### SuppFig S9 F,G,H
<img width="673" alt="image" src="https://github.com/user-attachments/assets/173f9b4b-32d8-49aa-9271-faf45028f7ea">
* _note: only change to F was x-axis values corrected to be in µm/hr_
* _note: only change to H was N value 

### SuppFig S10 (all)
<img width="680" alt="image" src="https://github.com/user-attachments/assets/cc29b145-d40d-4981-a56d-f3f476ffc7d8">

2024-11-26 20:52 UTC, chantelleleveille commented on nuc_morph_analysis/analyses/volume/FigS10_workflow.py
> +MAIN_TRACK_ID = 75725
Add track id to nuc_morph_analysis/lib/visualization/example_tracks.py

2024-11-26 20:52 UTC, chantelleleveille commented on nuc_morph_analysis/analyses/volume/FigS10_workflow.py
> +for ext in ['.png','.pdf']:
pdf only needed in the final version :)

2024-11-26 20:54 UTC, chantelleleveille commented on nuc_morph_analysis/analyses/volume/FigS10_workflow.py
> +    f.write(url)
This seems nice but I dont think it is necessary. We dont do this for the other figures made with TFE

2024-11-26 22:37 UTC, chantelleleveille requested changes
Great work Chris! So many figures!

The biggest thing is that loading data from scratch is not working. And then I think we could try to go through the features and be more selective about which ones are necessary and what we need to keep. I will give it a second pass once that function is working so I can test and read the code more interactively.

2024-11-26 22:37 UTC, chantelleleveille commented on nuc_morph_analysis/analyses/volume/FigS10_readme.md
> +global_dataset_filtering functions
Its nice to have all the definitions for features used. Are these the list of all of the new used features? If any are unused we should remove them from the dataframe. If they are used, we can move the feature definitions to the documentation.

2024-11-26 22:37 UTC, chantelleleveille commented on nuc_morph_analysis/analyses/volume/FigS10_workflow.py
> +fig,axlist = plot_tracks_aligned_at_volume_drop_onset(df_outliers,track_id_list,MAIN_TRACK_ID,TIMEPOINT)
How many of the example tracks are outliers? Hmm... it just seems odd to control for something that is in the outlier tracks.

2024-11-26 22:37 UTC, chantelleleveille commented on nuc_morph_analysis/analyses/volume/FigS10_workflow.py
> +df_outliers = load_dataset_with_features('all_baseline', remove_growth_outliers=False)
Sadly the load datasets from scratch is failing:

```
--> 283 df_full = filter_out_dips.run_script(df_full)
--> 406 dfd = df[
    407     ["colony", "track_id", "index_sequence", "label_img"] + volume_cols
    408 ].reset_index()

KeyError: "['fit_volume'] not in index"
```

2024-11-26 22:37 UTC, chantelleleveille commented on nuc_morph_analysis/analyses/volume/FigS10_workflow.py
> +# %%
Suggestion: it could be nice to ecapsulate each of these figure plots into a function to call in this workflow.

2024-11-26 22:37 UTC, chantelleleveille commented on nuc_morph_analysis/lib/preprocessing/global_dataset_filtering.py
> +    load_local=True,
Needs to be false. Loading from scratch is failing

2024-11-26 22:37 UTC, chantelleleveille commented on nuc_morph_analysis/lib/preprocessing/global_dataset_filtering.py
> +def add_volume_change_over_25_minute_window(df, bin_interval=5):
Move this to add_features.py

2024-11-26 22:37 UTC, chantelleleveille commented on nuc_morph_analysis/lib/preprocessing/compute_change_over_time.py
> +    # now we want to compute the difference
I dont totally understand what this function is for

2024-11-26 22:37 UTC, chantelleleveille commented on nuc_morph_analysis/lib/preprocessing/compute_change_over_time.py
> +def add_dvdt_over_V(df,columns=None,volume_col = 'volume'):
I think we dont want dvdt over V anymore. Can this go?

2024-11-26 22:37 UTC, chantelleleveille commented on nuc_morph_analysis/analyses/volume_variation/plot_features.py
> +    df_d = df_d.dropna(subset=[column_1, column_2]) # this step is necessary to get an accurate N value from len(df_d)
Nice catch

2024-11-26 22:37 UTC, chantelleleveille commented on nuc_morph_analysis/lib/visualization/write_data_for_colorizer_README.md
> +pdm run nuc_morph_analysis/lib/visualization/write_data_for_colorizer.py --output_dir //allen/aics/assay-dev/users/Frick/PythonProjects/repos/local_storage/timelapse_feature_explorer_datasets/TFE_new
oops remove these :)

2024-11-26 22:37 UTC, chantelleleveille commented on nuc_morph_analysis/lib/visualization/write_data_for_colorizer.py
>      ],
Can we prune the feature list to only include the ones analyzed or necessary to compute the features used in the paper!

2024-11-26 22:37 UTC, chantelleleveille commented on nuc_morph_analysis/analyses/volume/filter_out_dips.py
> +    parameters for the find peaks function in scipy
Can you talk about why you chose those defualt settings / what they mean

2024-11-26 22:37 UTC, chantelleleveille commented on nuc_morph_analysis/analyses/evaluate_filters_and_outliers/evaluate_time_binning.py
> +fig,ax = add_times.validate_dig_time_with_plot(old_method=True)
What is old method referring to?

2024-11-26 22:37 UTC, chantelleleveille commented on nuc_morph_analysis/analyses/neighbor_of_X/misc_neighbor_helper_functions.py
> +def get_a_cells_neighbors_as_track_id_list(df0,main_track_id,TIMEPOINT,return_self=True):
Nice :)

2024-11-26 22:46 UTC, chantelleleveille commented on nuc_morph_analysis/analyses/volume/FigS10_workflow.py
> +    f.write(url)
We also have a TFE links table in the docs section!! We can place the link there!

2024-11-27 18:24 UTC, jcass11 requested changes
Thanks for these extensive and well commented updates! 🎉 

 As @chantelleleveille commented we don't want to default to load local and since loading from scratch isn't working I can't test the workflows yet. Will happily test it all once that's cleared up!

2024-11-27 18:24 UTC, jcass11 commented on nuc_morph_analysis/analyses/evaluate_filters_and_outliers/evaluate_time_binning.py
> +fig,ax = add_times.validate_dig_time_with_plot(old_method=True)
And if its old why is it true? Would like to see old filters/methods/features that are replaced in analysis now just be eliminated from the code

2024-11-27 18:24 UTC, jcass11 commented on nuc_morph_analysis/analyses/neighbor_of_X/misc_neighbor_helper_functions.py
> +    # # compute distances between nuclei and sort them by distance to main track
can remove unused commented out code

2024-11-27 18:24 UTC, jcass11 commented on nuc_morph_analysis/analyses/volume/FigS10_workflow.py
> +for ext in ['.png','.pdf']:
Why? I usually do PDF

2024-11-27 18:24 UTC, jcass11 commented on nuc_morph_analysis/analyses/volume/FigS10_workflow.py
> +    f.write(url)
Agreed!

2024-11-27 18:24 UTC, jcass11 commented on nuc_morph_analysis/analyses/volume/FigS10_workflow.py
> +# S10 panel B, illustrate the effect of volume dip on transient growth rate
Love all the guiding comments

2024-11-27 18:24 UTC, jcass11 commented on nuc_morph_analysis/analyses/volume/FigS10_workflow.py
> +main_track_list = [(volume_dip_example_track, 263)] #[(86570, 263),(75725, 239), (71532,131)]
can remove unused commented out code

2024-11-27 18:24 UTC, jcass11 commented on nuc_morph_analysis/analyses/volume/FigS10_workflow.py
> +    # if threshold == -50:
can remove unused commented out code

2024-11-27 18:24 UTC, jcass11 commented on nuc_morph_analysis/analyses/volume/FigS10_workflow.py
> +    # savepath = figdir / f"cell_cycle_bins_{ycol}_{xcol1}_{plot_type}.png"
can remove unused commented out code

2024-11-27 18:24 UTC, jcass11 commented on nuc_morph_analysis/analyses/volume/figure_5_s9_workflow.py
> +    # savepath = figdir / f"cell_cycle_bins_{ycol}_{xcol1}_{plot_type}.png"
can remove unused commented out code

2024-11-27 18:24 UTC, jcass11 commented on nuc_morph_analysis/analyses/volume/filter_out_dips.py
> +    # keys = ['volume_dips_peak_mask_at_region','volume_dips_centers','volume_dips_has_peak','volume_dips_prom','volume_dips_left_base','volume_dips_right_base','volume_dips_y2_magnitude']
can remove unused commented out code

2024-11-27 18:24 UTC, jcass11 commented on nuc_morph_analysis/analyses/volume/filter_out_dips.py
> +    STEPS:
So nice thank you

2024-11-27 18:24 UTC, jcass11 commented on nuc_morph_analysis/analyses/volume/filter_out_dips.py
> +    # interpolate the missing internal nan values while keeping the beginning and ending stretch of nans
wow the extensive comments are just so nice

2024-11-27 18:24 UTC, jcass11 commented on nuc_morph_analysis/analyses/volume/plot_help.py
> +        print(width,height,fw,fh)
Can we remove this? I like to avoid print statements that just outputs numbers with no context

2024-11-27 18:24 UTC, jcass11 commented on nuc_morph_analysis/lib/preprocessing/add_times.py
> +    if old_method:
Can we remove old methods and just use new ones?

2024-11-27 18:24 UTC, jcass11 commented on nuc_morph_analysis/lib/visualization/write_data_for_colorizer.py
> +    # df_all2 = df_all.copy()
can remove unused commented out code

2024-11-27 18:37 UTC, chantelleleveille commented on nuc_morph_analysis/analyses/volume/FigS10_workflow.py
> +for ext in ['.png','.pdf']:
I meant dont need png. Sorry

2024-11-27 22:01 UTC, jcass11 commented
I think the commit @cfrick13 added today was intended to fix the loading from scratch so I am going ahead and test running the two new workflow (and if they run I will then also do a full `run_all_manuscript_workflows.py` test run. Thanks Chris!

2024-11-27 22:35 UTC, jcass11 commented
The `figure_5_s9_workflow` runs without errors 🎉 

Scanning through output figures I think they're looking good. The font sizes are out of scale on the cell_cycle_bin output figures but maybe that's an expected outcome for how they need to be generated to be exported and sized correctly in the illustrator file.

The workflow currently returns quite a lot of output to the terminal. Are these print statements leftover from debugging or are they used for a manual step afterwards? I'd love for the output to not include numbers without context (for example many of the outputs looks like this:
```
Late 10 71 37.0750605327 15312 t= 413                                                                                     
0.9 0.6 6.5 8.0                                                                                                           
0.9 0.6 6.5 8.0                                                                                                           
0.9 0.6 6.5 8.0                                                                                                           
0.9 0.6 6.5 8.0
```
) which seems like maybe a combo of redundant and unannotated output. 

So if all the print statements could be (a) only included if they are still important/somehow manually used afterwards and (b) have annotations to the numbers so that they're a little more meaningful to the user that would be great!

2024-12-04 17:25 UTC, jcass11 commented on nuc_morph_analysis/analyses/volume/FigS10_workflow.py
> +# %%
It would be but now with a couple days to our deadline I'd say we can save this for a future PR

2024-12-04 17:30 UTC, jcass11 commented on nuc_morph_analysis/lib/preprocessing/global_dataset_filtering.py
> +    load_local=True,
```suggestion
    load_local=False,
```

2024-12-05 00:43 UTC, cfrick13 commented
### updates
I made a few more edits to add clarity and then merged the dev branch. 

### tests
Reran `write_data_for_colorizer.py` successfully. 
Rerunning `run_all_manuscript_worfklows.py`.

2024-12-05 00:48 UTC, jcass11 commented on nuc_morph_analysis/lib/visualization/write_data_for_colorizer_README.md
> +pdm run nuc_morph_analysis/lib/visualization/write_data_for_colorizer.py --output_dir //allen/aics/assay-dev/users/Frick/PythonProjects/repos/local_storage/timelapse_feature_explorer_datasets/TFE_new
Weird I thought my PR removed these!

2024-12-05 00:49 UTC, chantelleleveille approved these changes

2024-12-05 00:53 UTC, jcass11 approved these changes
Took a look through all the files and it looks great! Did not re-test since it sounds like you're on top of that

2024-12-05 01:03 UTC, cfrick13 commented
update:
====== Successes ======
figure_1_dataset (393.7s) (50.8GB)
figure_3_s4_height_density (317.3s) (44.6GB)
figure_4_s8_volume_trajectories (67.1s) (27.1GB)
figure_6_s11_compensation (77.9s) (27.1GB)
figure_7_s13_s14_lineage (259.2s) (27.1GB)
figure_s12_feeding_control (86.2s) (20.3GB)
figure_s15_linear_regression_model (1460.5s) (27.1GB)
figure_s19_transition_point (15.4s) (27.2GB)
figure_s1_cell_health (13.5s) (23.7GB)
figure_s20_precision_error (7.2s) (5.3GB)
figure_s2_s3_s18_segmentation_model_validation (155.9s) (8.4GB)
figure_s7_growth_outliers (78.3s) (27.9GB)
====== Failures ======
figure_5_s9_s10_local_growth (154.7s) (43.9GB). TypeError expected string or bytes-like object. See stack trace above.
figure_s6_s16_inhibitors (29.6s) (13.4GB). AssertionError . See stack trace above.
====== 12 succeeded 2 failed ======

2024-12-05 01:13 UTC, cfrick13 commented
====== figure_5_s9_s10_local_growth ======
Traceback (most recent call last):
  File "/allen/aics/assay-dev/users/Frick/PythonProjects/repos/nucmorph_dev/nuc-morph-analysis/nuc_morph_analysis/utilities/workflow_runner.py", line 38, in _runjob
    job()
  File "/allen/aics/assay-dev/users/Frick/PythonProjects/repos/nucmorph_dev/nuc-morph-analysis/run_all_manuscript_workflows.py", line 43, in figure_5_s9_s10_local_growth
    import nuc_morph_analysis.analyses.volume.FigS10_workflow
  File "/allen/aics/assay-dev/users/Frick/PythonProjects/repos/nucmorph_dev/nuc-morph-analysis/nuc_morph_analysis/analyses/volume/FigS10_workflow.py", line 123, in <module>
    axlist = type_axlist(axlist_untyped)
  File "/allen/aics/assay-dev/users/Frick/PythonProjects/repos/nucmorph_dev/nuc-morph-analysis/nuc_morph_analysis/lib/visualization/matplotlib_to_axlist.py", line 21, in type_axlist
    plt_axis_list = cast(List[Axes], cast(NDArray, plt_axis_np).tolist())
AttributeError: 'list' object has no attribute 'tolist'
====== Failures ======
figure_5_s9_s10_local_growth (161.4s) (39.6GB). AttributeError 'list' object has no attribute 'tolist'. See stack trace above.
======  1 failed ======

2024-12-05 16:43 UTC, cfrick13 commented
Got it working! Will merge now!
====== Successes ======
figure_5_s9_s10_local_growth (236.4s) (41.3GB)
====== 1 succeeded  ======

2024-12-05 16:52 UTC, merged